<?xml version="1.0"?>
<robot xmlns:xacro="http://www.ros.org/wiki/xacro">
    <!--Import parts from xacro file-->
    <xacro:include filename="../module_xacro/overconstrained_left.urdf.xacro"/>

    <xacro:property name="radius" value="0.1"/>

    <link name="dummy">
        <inertial>
            <mass value="0"/>
            <inertia ixx="0.0" ixy="0.0" ixz="0.0" iyy="0.0" iyz="0.0" izz="0.0"/>
        </inertial>
    </link>

    <link name="z_offset_link">
        <inertial>
            <mass value="0"/>
            <inertia ixx="0.0" ixy="0.0" ixz="0.0" iyy="0.0" iyz="0.0" izz="0.0"/>
        </inertial>
    </link>

    <joint name="z_offset" type="fixed">
        <parent link="dummy"/>
        <child link="z_offset_link"/>
        <origin xyz="0 0 0.0" rpy="0 0 0"/>
    </joint>

    <!-->
                module 4

       module1  . origin  module 3

                 module 2
    <-->

    <xacro:module_overconstrained_left module_prefix="0" parent_link="z_offset_link">
        <origin xyz="${-1*radius} 0 0" rpy="${PI} 0 ${PI/2.0}"/>
    </xacro:module_overconstrained_left>

    <xacro:module_overconstrained_left module_prefix="1"  parent_link="z_offset_link">
        <origin xyz="${radius} 0 0" rpy="${PI} 0 ${-1*PI/2.0}"/>
    </xacro:module_overconstrained_left>

</robot>